package seleniumProject;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class AlertBox {

	public static void main(String[] args) throws InterruptedException {
		// TODO Auto-generated method stub
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\Lenovo\\Downloads\\chromedriver_win32\\chromedriver.exe");
		WebDriver driver= new ChromeDriver();
		driver.get("https://demo.automationtesting.in/Alerts.html");
		//case 1:
		driver.findElement(By.xpath("//a[normalize-space()='Alert with OK']")).click();
		driver.findElement(By.xpath(" //button[contains(text(),'click the button to display an')]")).click();
		driver.switchTo().alert().accept();//accepting the alert generated by previous action
		Thread.sleep(4000);
		
		/*  
		
		
		
		
		// case2: 
		driver.findElement(By.xpath("//a[normalize-space()='Alert with OK & Cancel']")).click();
		driver.findElement(By.xpath("//button[@class='btn btn-primary']")).click();
		driver.switchTo().alert().accept(); // click on OK
		
		Thread.sleep(4000);
		
		driver.findElement(By.xpath("//a[normalize-space()='Alert with OK & Cancel']")).click();
		driver.findElement(By.xpath("//button[@class='btn btn-primary']")).click();
		driver.switchTo().alert().dismiss(); // click on Cancel
		
		
		driver.findElement(By.xpath("//a[normalize-space()='Alert with Textbox']")).click();
		driver.findElement(By.xpath("//button[@class='btn btn-info']")).click();
		driver.switchTo().alert().accept(); // click on OK
		
		Thread.sleep(4000);
		String actualvalueOK= driver.findElement(By.xpath("//p[@id='demo1']")).getText();
		Assert.assertEquals("Hello Automation Testing user How are you today", actualvalueOK) ;
		
		
		driver.findElement(By.xpath("//a[normalize-space()='Alert with Textbox']")).click();
		driver.findElement(By.xpath("//button[@class='btn btn-info']")).click();
		driver.switchTo().alert().dismiss(); // click on cancel
		
		Thread.sleep(4000);
		String actualvalueCancel= driver.findElement(By.xpath("//p[@id='demo1']")).getText();
		System.out.println("value of cancel"+actualvalueCancel);
		Assert.assertEquals("", actualvalueCancel) ;
		
		driver.findElement(By.xpath("//a[normalize-space()='Alert with Textbox']")).click();
		driver.findElement(By.xpath("//button[@class='btn btn-info']")).click();
		
		
		driver.close();
		Thread.sleep(4000);
		
		}
		catch (Exception e) {
			System.out.println(e);
		 */

	}

}
